# Generated by Django 4.1a1 on 2022-05-28 07:12

from django.db import migrations, models
import django.db.models.deletion
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "organizer",
                    models.CharField(blank=True, default="NDRF", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    thumbnails.fields.ImageField(blank=True, upload_to="event_images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("N", "NCC"),
                            ("NS", "NSS"),
                            ("S", "Student"),
                            ("O", "Other"),
                        ],
                        default="N",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("street", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=50)),
                (
                    "volunteer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="backend.volunteer",
                    ),
                ),
            ],
        ),
    ]
