# Generated by Django 4.1a1 on 2022-06-01 12:52

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                default=django.utils.timezone.now, upload_to="files/resources"
            ),
            preserve_default=False,
        ),
    ]
