# Generated by Django 4.1a1 on 2022-06-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_resource_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="size",
        ),
    ]
