# Generated by Django 4.1a1 on 2022-06-03 06:16

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_remove_resource_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="address",
        ),
        migrations.AlterField(
            model_name="resource",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="files/resources/cache"
            ),
        ),
    ]
