# Generated by Django 4.1a1 on 2022-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_resource_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
