# Generated by Django 4.1a1 on 2022-06-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_resource_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
